//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub parent_id: i32,
    pub created_at: DateTimeLocal,
    pub updated_at: DateTimeLocal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::article_category::Entity")]
    ArticleCategory,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl Related<super::article_category::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ArticleCategory.def()
    }
}

impl Related<super::article::Entity> for Entity {
    fn to() -> RelationDef {
        super::article_category::Relation::Article.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::article_category::Relation::Category.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
