//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

/// Entity prelude module 提供增删改查方法的类型
pub use super::admin::Entity as AdminEntity;
pub use super::article::Entity as ArticleEntity;
pub use super::article_category::Entity as ArticleCategoryEntity;
pub use super::article_tag::Entity as ArticleTagEntity;
pub use super::category::Entity as CategoryEntity;
pub use super::comment::Entity as CommentEntity;
pub use super::jwt::Entity as JwtEntity;
pub use super::tag::Entity as TagEntity;
pub use super::website::Entity as WebsiteEntity;

/// Model prelude module 数据库查询输出（只读）类型
pub use super::admin::Model as Admin;
pub use super::article::Model as Article;
pub use super::article_category::Model as ArticleCategory;
pub use super::article_tag::Model as ArticleTag;
pub use super::category::Model as Category;
pub use super::comment::Model as Comment;
pub use super::jwt::Model as Jwt;
pub use super::tag::Model as Tag;
pub use super::website::Model as Website;

/// ActiveModel prelude module 数据库增删改（读写）类型
pub use super::admin::ActiveModel as ActiveAdmin;
pub use super::article::ActiveModel as ActiveArticle;
pub use super::article_category::ActiveModel as ActiveArticleCategory;
pub use super::article_tag::ActiveModel as ActiveArticleTag;
pub use super::category::ActiveModel as ActiveCategory;
pub use super::comment::ActiveModel as ActiveComment;
pub use super::jwt::ActiveModel as ActiveJwt;
pub use super::tag::ActiveModel as ActiveTag;
pub use super::website::ActiveModel as ActiveWebsite;
