//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "admin")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Binary(255)")]
    pub password: Vec<u8>,
    pub nickname: Option<String>,
    pub email: Option<String>,
    pub github: Option<String>,
    pub wechat: Option<String>,
    pub qq: Option<String>,
    pub avatar: Option<String>,
    pub created_at: DateTimeLocal,
    pub updated_at: DateTimeLocal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::jwt::Entity")]
    Jwt,
}

impl Related<super::jwt::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Jwt.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
