//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

mod prelude;
pub use prelude::*;

pub mod admin;
pub mod article;
pub mod article_category;
pub mod article_tag;
pub mod category;
pub mod comment;
pub mod jwt;
pub mod tag;
pub mod website;
