[package]
name = "deepseek"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
reqwest = { version = "0.12.12", features = ["json", "rustls-tls", "stream"] }
derive_builder = { version = "0.20.2", features = ["clippy"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.11"
futures = "0.3.31"
bytes = "1"
reqwest-middleware = { version = "0.4.0", features = [
    "charset",
    "json",
    "rustls-tls",
] }
reqwest-retry = "0.7.0"
reqwest-tracing = "0.5.5"
tokio = { version = "1", features = ["rt", "macros", "fs", "rt-multi-thread"] }

[dev-dependencies]
anyhow = "1"
dotenvy = "0.15.7"
