[package]
name = "deepseek"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
reqwest = { version = "0.12.12", features = ["json", "rustls-tls", "stream"] }
derive_builder = { version = "0.20.2", features = ["clippy"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1"
dotenvy = "0.15.7"
thiserror = "2.0.11"
futures = "0.3.31"
bytes = "1.9.0"

[dev-dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt", "macros", "fs", "rt-multi-thread"] }
