[package]
name = "common"
authors.workspace = true
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
rsa = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
redis = { workspace = true }
bb8 = { workspace = true }
bb8-redis = { workspace = true }
redis-macros = { workspace = true }
rustls = { workspace = true }
infer = { workspace = true }
