[package]
name = "api"
authors.workspace = true
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
service = { path = "../service" }
tower-http = { workspace = true }
tower = { workspace = true }
sea-orm = { workspace = true }
setting = { path = "../setting" }
